name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      name: Check code on this fresh Ubuntu OS
      uses: actions/checkout@v4

      name: Log in to Docker Hub
      uses: docker/login-action@v2
